### ISSUE TITLE
Oberon language support

### ISSUE THREAD

**Issue by rsdoiel** [github-linguist/linguist#5422]
## Language name

Oberon, Oberon-2, Oberon-7

## URL of example repository

https://github.com/rsdoiel/helloworld-oberon

## Most popular extensions

.Mod, .m, .obn

## Detected language

Oberon modules have the text of "MODULE " followed by the module name and semicolon. The only thing that can come before "MODULE " is a comment. Comments
in Oberon are delimited by paren asterix ` (* this is a comment *)  `. There will be a
"END " followed by the module name and period. Module names usually match the filename minus the extension.  Example module

~~~
(* optional opening comments, usually description and license info *)
MODULE MyThing;

(* bunch of code *)

END MyThing.
~~~

**Comment by lildude** [comment]
A PR already exists but usage wasn't sufficient at the time https://github.com/github/linguist/pull/4645
