### ISSUE TITLE
Add Language: Luau

### ISSUE THREAD

**Issue by RBXTyler** [github-linguist/linguist#6000]
## Language name
"Luau"
https://luau-lang.org

## URL of syntax highlighting grammar
https://luau-lang.org/syntax

## Most popular extensions
`.luau`

**Comment by checkraisefold** [comment]
Should be able to use a slightly modified version of https://github.com/NightrainsRbx/RobloxLsp/blob/master/syntaxes/lua.tmLanguage.json for the grammar. The question is whether to use it slightly modified (removing Roblox globals to better match the outside-Roblox usage) or to keep them, considering usage on Roblox is more common.

**Comment by lildude** [comment]
Bumming won’t make it happen any faster… we need someone in the community to actually put the work in and submit a PR 😁
