### ISSUE TITLE
Add Language: Carbon

### ISSUE THREAD

**Issue by JuniorCode** [github-linguist/linguist#6013]
## Language name

Carbon

## URL of syntax highlighting grammar

https://github.com/carbon-language/carbon-lang/blob/trunk/utils/textmate/Syntaxes/Carbon.plist

## Most popular extensions

`.carbon`, `.carb`, `.cb`

**Comment by DecimalTurn** [comment]
Related https://github.com/github-linguist/linguist/pull/7011
