### ISSUE TITLE
Distinguish "Rez" sources from R

### ISSUE THREAD

**Issue by cooljeanius** [github-linguist/linguist#6107]
## Language name
"Rez" was a language for generating resources for classic MacOS applications. Apple might not officially support it any longer, but it still gets some use among people into retro-computing and historical software.

## URL of example repository
- https://github.com/uliwitness/mpw-sillyballs
- https://github.com/cooljeanius/Glypha-III

## URL of syntax highlighting grammar
I'm not aware of any FOSS ones, but syntax highlighting for Rez sources is still supported in Xcode as of Xcode 13. It's kind of C-like. 

## Most popular extensions
`.r`

## Detected language
R

## Links
- http://preserve.mactech.com/articles/mactech/Vol.14/14.09/RezIsYourFriend/index.html
- https://www.unix.com/man-page/osx/1/Rez/
- https://github.com/uliwitness/ulisworldwdef/blob/master/FatCodeResource.r
- http://web.archive.org/web/20211113094506/https://twitter.com/uliwitness/status/1459457263605895168

**Comment by uliwitness** [comment]
Current versions of macOS X still include the `Rez` and `DeRez` command line tools for consuming and generating this type of files.

**Comment by ryandesign** [comment]
Yes, please. Rez files are still used today by retro computing enthusiasts creating new classic Mac OS applications such as https://github.com/cy384/ssheven.

To show that Rez is a valid language in use in more than just a few places, here is a search that shows a subset of Rez files on GitHub that define `DITL` resources (dialog item lists). Most of these are being misidentified as "R" and some as "Rebol". Not all Rez files define dialog item lists so there will be more Rez files out there that are not found by this search, but the string "DITL" seemed like it would be unique to Rez files and not turn up any real R or Rebol files.

https://github.com/search?type=Code&q=extension%3Ar+DITL

Here's a search of Rez files that define a `vers` (version) resource that specifies `verUS` (localized for the United States):

https://github.com/search?type=Code&q=extension%3Ar+verUS

These searches turn up 3-4 thousand files each, though of course there is duplication where a popular project is copied in many repositories.

I see that linguist's R syntax support comes from a TextMate bundle, as does the support for many other languages. TextMate also has a Rez syntax bundle: https://github.com/textmate/rez.tmbundle. Could it be as simple as just adding that to a list somewhere?

**Comment by cooljeanius** [comment]
> Yes, please. Rez files are still used today by retro computing enthusiasts creating new classic Mac OS applications such as [cy384/ssheven](https://github.com/cy384/ssheven).

another example: autc04/Retro68

**Comment by cooljeanius** [comment]
ok I opened #6524 for this; still need help picking a color, though...

**Comment by cooljeanius** [comment]
> ok I opened #6524 for this; still need help picking a color, though, and also adding a pattern to the heuristics file...

ok so #6524 is merged now as of [55cfb49](https://github.com/github-linguist/linguist/commit/55cfb4961c1202dd1d4e94ca6623d0f81f297b66); I guess if there are any further issues regarding detection of "Rez", they can get separate issues...
