### ISSUE TITLE
Add nushell support

### ISSUE THREAD

**Issue by hustcer** [github-linguist/linguist#6214]
## Language name

nushell

## URL of example repository

https://github.com/nushell/nu_scripts

## URL of syntax highlighting grammar

https://github.com/nushell/vscode-nushell-lang

## Most popular extensions

`.nu`

## Detected language

https://github.com/programming-nu/nu

**Comment by Araxeus** [comment]
Funnily enough `nu` is already reserved for something else (I can't even figure out what is that)

https://github.com/github/linguist/blob/5a0c74277548122267d84283910abd5e0b89380e/lib/linguist/languages.yml#L4488-L4503

**Comment by hustcer** [comment]
Since https://github.com/github-linguist/linguist/pull/6403 was merged, Github has Nushell syntax highlighting support now. But I have another question @lildude : Why https://github.com/nushell/nu_scripts 's `Languages` section displays `Nu` and `Other`, I thought it should be `Nushell` and `Other`, Is there anything else should I do?

**Comment by hustcer** [comment]
> Why https://github.com/nushell/nu_scripts 's `Languages` section displays `Nu` and `Other`, I thought it should be `Nushell` and `Other`, Is there anything else should I do?

Syntax highlighting for Nushell works pretty well. However, this issue still exists, did I miss anything?

**Comment by lildude** [comment]
> did I miss anything?

[Yup, these first two sentences](https://github.com/github-linguist/linguist/blob/master/docs/how-linguist-works.md#how-linguist-works-on-githubcom) 😉
