### ISSUE TITLE
Add Language: Typst

### ISSUE THREAD

**Issue by rami3l** [github-linguist/linguist#6358]
## Language name

[Typst](https://github.com/typst/typst)

## URL of example repository

https://github.com/wusyong/resume.typ

## URL of syntax highlighting grammar

https://raw.githubusercontent.com/nvarner/typst-lsp/master/addons/vscode/typst.tmLanguage.json

## Most popular extensions

`.typ`

## Detected language

N/A

**Comment by Alhadis** [comment]
Looks like `.typ` is a [pretty common](https://github.com/search?q=path%3A**%2F%3F*.typ+-lang%3Axml+-lang%3Asql&type=code) file extension… and not amongst Typst users…

Something tells me that supporting this will require some prickly heuristics…

**Comment by DecimalTurn** [comment]
@pablodz, the `path` field is only available with the new GitHub code search. Normally, you can add it via going `top-right menu > Feature preview` and activating `New Code Search and Code View`.

**Comment by rami3l** [comment]
> Looks like `.typ` is a [pretty common](https://github.com/search?q=path%3A**%2F%3F*.typ+-lang%3Axml+-lang%3Asql&type=code) file extension… and not amongst Typst users…
> 
> Something tells me that supporting this will require some prickly heuristics…

Looking at the search result I guess most Typst files can be detected with `#import`, `#show`, `#let`, `#set`, etc.

Maybe the creators of the language can share some more insights on this? 🙏 

cc @laurmaedje @reknih

**Comment by rami3l** [comment]
@michidk [The search result](https://github.com/search?q=path%3A**%2F%3F*.typ+-lang%3Axml+-lang%3Asql+%2F%23%28let%7Cset%7Cshow%29%2F&type=code) already gives 1.5k+ files, so hopefully we can close this issue in the coming months!
