### ISSUE TITLE
Notice: This repository will be moving to the github-linguist organisation

### ISSUE THREAD

**Issue by lildude** [github-linguist/linguist#6374]
# This repository is moving!!!

**Why?**

In a bid to improve security of GitHub's primary organisation https://github.com/github, GitHub is moving all repositories with outside collaborators out of the organisation. This repository is one of those.

**When?**

There is no specific date, but it will be before the end of April 2023.

**What will happen?**

The repository will be moved to the new organisation at https://github.com/github-linguist/linguist (there's nothing there right now).

All current external contributors will retain their access.

Old external contributors will lose their access, if they haven't already.

All PRs should automatically rebase to the new repository location so you shouldn't need to do anything. If they don't please open an issue and I'll try sort things out.

All issues and discussions will be moved across at the same time too.

All documentation links on docs.github.com will also be updated to link to the new location.

This will also be posted and pinned in the Discussions.

**Comment by Alhadis** [comment]
Makes sense to me. 🤔 (Though I'm surprised to learn that I was never added to the @github-linguist org…)

**Comment by DecimalTurn** [comment]
Seems like the most important things are preserved. 
![anigif_sub-buzz-8420-1569207598-1](https://github.com/github/linguist/assets/31558169/32d5bb59-f829-47ab-bbc9-c7cf414ac8fb)

Will it affect forks however?

**Comment by lildude** [comment]
> Will it affect forks however?

No, forks should remain linked.

**Comment by lildude** [comment]
This has now happened and all looks good from a quick look.
