### ISSUE TITLE
Fix highlighting for Java

### ISSUE THREAD

**Issue by iceBear67** [github-linguist/linguist#6398]
## Describe the bug

Java uses syntax highlighting rules that are inconsistent with those in the README.
PR #5932 says that GitHub uses tree-sitter as the Java syntax parser. Java has been using java.tmBundle (which has been out of date for years),

## Expected behaviour

Correct the vendor for Java.

**Comment by lildude** [comment]
This isn't really on Linguist to resolve as GitHub is definitely using the tree-sitter grammar for highlighting Java files. It is not using the TextMate-compatible grammar Linguist ships with, which is now only kept for use by other grammar and third party products which use linguist.

> Java uses syntax highlighting rules that are inconsistent with those in the README.

In what way? Is there a bug and fix already in the upstream tree-sitter grammar?

I ask as the tree-sitter grammar updates are handled by the team that maintains the highlighting engine, and whilst it's likely it's using an old version, they don't regularly pull in updates unless there's a good reason to, like an explicit bug fix, to keep things consistent and stable.

**Comment by iceBear67** [comment]
I think my expression is a bit ambiguous. The reason I think GitHub is still using the TextMate Bundle is because GitHub's syntax highlighting, like the TextMate Bundle, doesn't have support for newer syntax features like the keyword record sealed var, whereas tree-sitter-java has already added their support

Maybe it's time for them to update

**Comment by lildude** [comment]
That's still quite ambiguous to someone (me) that doesn't know Java or what a "keyword record sealed var" is 😂

Can you provide a codeblock with an example?

> whereas tree-sitter-java has already added their support

Do you have a PR I can refer to?

**Comment by iceBear67** [comment]
Sorry, here are some examples:

1. [Record](https://openjdk.org/jeps/395)

```java
record Range(int lo, int hi) {
    Range {
        if (lo > hi)  // referring here to the implicit constructor parameters
            throw new IllegalArgumentException(String.format("(%d,%d)", lo, hi));
    }
}
```

2.[Sealed Classes](https://openjdk.org/jeps/409)
```java
sealed interface Celestial 
    permits Planet, Star, Comet { ... }

final class Planet implements Celestial { ... }
final class Star   implements Celestial { ... }
final class Comet  implements Celestial { ... }
```

3. [var](https://openjdk.org/jeps/286)
```java
var path = Paths.get(fileName); // instead of Path path = ....
var bytes = Files.readAllBytes(path);
```

4. [when](https://openjdk.org/jeps/441)
```java
// As of Java 21
static void testStringNew(String response) {
    switch (response) {
        case null -> { }
        case String s
        when s.equalsIgnoreCase("YES") -> {
            System.out.println("You got it");
        }
        case String s
        when s.equalsIgnoreCase("NO") -> {
            System.out.println("Shame");
        }
        case String s -> {
            System.out.println("Sorry?");
        }
    }
}
```

5.[yield](https://openjdk.org/jeps/361)
```java
int j = switch (day) {
    case MONDAY  -> 0;
    case TUESDAY -> 1;
    default      -> {
        int k = day.toString().length();
        int result = f(k);
        yield result;
    }
};
```


>    whereas tree-sitter-java has already added their support

> Do you have a PR I can refer to?

I actually didn't go looking for a specific PR, because missing syntax features are usually submitted in multiple PRs, and I found this in their code.

1. sealed classes: https://github.com/tree-sitter/tree-sitter-java/blob/c194ee5e6ede5f26cf4799feead4a8f165dcf14d/grammar.js#L826-827
2. records: https://github.com/tree-sitter/tree-sitter-java/blob/c194ee5e6ede5f26cf4799feead4a8f165dcf14d/grammar.js#L870-872
3. "var": https://github.com/tree-sitter/tree-sitter-java/blob/c194ee5e6ede5f26cf4799feead4a8f165dcf14d/grammar.js#LL1166C1-L1166C1
4. ....

**Comment by lildude** [comment]
GitHub's syntax highlighter was updated to use the latest SHA of the grammar repo on 11 May so you should see a difference though it can be hard to see some as it'll depend on the appearance setting you use and GitHub's choice of colours (Linguist and the grammar have no direct control over this, though the grammar could get creative to force GitHub to use different colour 😉).

Using the default dark theme (as it's a little easier to see), we can see that `sealed` (very clear) and `var` are now highlighted:

![CleanShot 2023-06-19 at 15 31 02](https://github.com/github-linguist/linguist/assets/627280/11450eaa-ac2a-4cd3-85e4-05f5dbc9994f)

The latter is very slightly different, but you can see in the source it's different:

![CleanShot 2023-06-19 at 14 55 31](https://github.com/github-linguist/linguist/assets/627280/bdd82daa-8d6a-4e4a-82a7-172470558081)

- `var` => `pl-smi` => `rgb(201, 209, 217)`
- `path` => `pl-s1` => `rgb(230, 237, 243)`

`when` is being highlighted, however the grammar has declared it the same as a string like the `path` line above and the `s` next to it. You can see this in the HTML source:

![CleanShot 2023-06-19 at 15 36 27](https://github.com/github-linguist/linguist/assets/627280/68ea13ff-ba05-4b1f-b311-0fe8e590a02e)

This leaves `record` and `yield`. Looking at the source, I can see these aren't highlighted at all which would indicate the theme hasn't told us how to handle these differently:

![CleanShot 2023-06-19 at 15 41 05](https://github.com/github-linguist/linguist/assets/627280/260c3a18-76e3-4d78-a5c0-140d5c516789)

![CleanShot 2023-06-19 at 15 41 25](https://github.com/github-linguist/linguist/assets/627280/0b30a11e-9eb1-405f-821e-bc8034702889)

I installed the `tree-sitter-cli` tool, and used it with this grammar to highlight a file containing all your examples and I get the same result as GitHub currently shows (with different, and more obvious colours) which confirms the lack of differentiation is down to the grammar:

![Screenshot showing syntax highlighting](https://github.com/github/treelights/assets/627280/6f3350ad-d835-43c3-b631-20b06f133481)

So at is stands, all remaining issues are with the grammar so you'll need report the outstanding problems with the grammar maintainers.

Closing as the remaining issues need addressing in the upstream grammar and not Linguist.

**Comment by iceBear67** [comment]
Thanks!
