### ISSUE TITLE
linguist-language=Markdown versus .md file extension

### ISSUE THREAD

**Issue by szepeviktor** [github-linguist/linguist#6411]
## Describe the bug

There is a difference in rendering the very same content.

.md extension works as expected.
https://github.com/szepeviktor/BracketSpace_Advanced-Cron-Manager/blob/readmeee/readme.txt.md

linguist-language=Markdown in gitattributes fails.
https://github.com/szepeviktor/BracketSpace_Advanced-Cron-Manager/blob/7e64255753f067422c1eae22f21326cbabf13fc9/readme.txt

What should I put into gitattributes to produce the same output as an .md file?
Thank you!

### Expected behaviour

Same output for both.

**Comment by szepeviktor** [comment]
See the work-around in https://github.com/github/markup/issues/1069#issuecomment-460056003

**Comment by lildude** [comment]
Duplicate of https://github.com/github-linguist/linguist/issues/6331
