### ISSUE TITLE
add syntax color to jsdoc variables

### ISSUE THREAD

**Issue by jimmywarting** [github-linguist/linguist#6426]
VScode dose a wonderful job at highlighting JSDoc variable names so they are easier to read

here is an example of how VSCode syntax color looks like:

![image](https://github.com/github-linguist/linguist/assets/1148376/5fae53fe-3355-47bf-9b32-3a1aca8ed06f)

```js
/**
 * And this is how github markdown pressents it
 * 
 * @param {number} x This is a comment
 * @param {number} [y] this is another optional comment
 */
function add (x, y) {

}
```
All the comments being gray is fine, but i would wish for the variable name to be colored

ppl don't always include a `-` to separate out the variable name from the actual comment
like this:
```
 * @param {number} x - This is a comment
```
so it looks a bit weird as if the variable name is sometimes part of the actual comment in some cases

**Comment by lildude** [comment]
All syntax highlighting is determined by third-party grammars. As such, you need to raise this with the maintainer of the repo in question. See the [docs](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file) for more details.

It's not documented in this repo (as we don't differentiate JSDoc from JavaScript), but GitHub actually uses the https://github.com/tree-sitter/tree-sitter-jsdoc grammar for JSDoc so you'll need to open an issue in that repo.

Closing as this is out of Linguist's control entirely.

**Comment by jimmywarting** [comment]
Ty for point me in the right direction
