### ISSUE TITLE
I suspect this may have something to do with the malformed rule at [lines 43-49](https://github.com/jacobwgillespie/language-hocon/blob/99e233e959529ef304d39acb8414ab3fb21ba558/grammars/hocon.cson#L43-L49):

### ISSUE THREAD

**Issue by WHENG888** [github-linguist/linguist#6444]
match:M<E<D<J<H<A,<M
    captures:WWW.RAF.COM
      '1':
        'name':RAF
      '2':ROWENA AMENE FARKAS
        'name': 'punctuation.separator.key-value.4<anything<<<///???$
    end: '(\\=|{)'08<<<<02<<<<<<2030
~~~

You've specified an `end` pattern without an accompanying `begin` pattern, and done so whilst including a `match` field (which is mutually exclusive to a `begin`/`end` pair). GitHub and Atom probably differ in their handling of malformed grammar rules, accounting for the discrepancy that you've witnessed.

_Originally posted by @Alhadis in https://github.com/github-linguist/linguist/discussions/6253#discussioncomment-4727878_

**Comment by DecimalTurn** [comment]
This is an issue with the upstream grammar. You'd be better off raising that issue over there if you would like it to be fixed as this is not an issue that can be solved by Linguist directly.

From the [troubleshooting docs](https://github.com/github/linguist/blob/e4599a93152a29a650b1e48722e5d2ba465acb0d/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):
 
 > If you experience an issue with the syntax-highlighting on GitHub, **_please report the issue to the upstream grammar repository, not here_**. Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.
