### ISSUE TITLE
.gradle.kts files should not be listed as Kotlin code

### ISSUE THREAD

**Issue by mikewacker** [github-linguist/linguist#6469]
## Describe the bug

Gradle has two DSLs for writing build code, one based on Groovy, and one based on Kotlin.

- Files using the Groovy DSL [`.gradle`] do not get listed as Groovy code.
- Files using the Kotlin DSL [`.gradle.kts`] get listed as Kotlin code.

In both cases, build code should not count as code in the code stats.

See: https://github.com/github-linguist/linguist/blob/e855ef2b6f90c34074061a2e17acbe853e61b483/lib/linguist/languages.yml#L2519-L2526

### Expected behaviour

Files using the Kotlin DSL [`.gradle.kts`] do not get listed as Kotlin code. (E.g., `build.gradle.kts`)

### Related discussion

https://github.com/github-linguist/linguist/discussions/5352

**Comment by DecimalTurn** [comment]
This seems like an easy fix:

```diff
   extensions: 
   - ".gradle" 
+  - ".gradle.kts" 
   tm_scope: source.groovy.gradle 
```

Something similar is already done for Antlers and Blade for instance.

**Comment by mikewacker** [comment]
@DecimalTurn 

We would still want to treat `.gradle.kts` files as Kotlin code for other purposes. E.g., if you [view a `build.gradle` file in Github](https://github.com/palantir/palantir-java-format/blob/develop/build.gradle), it does have syntax highlighting for Groovy.

Not a linguist expert, but I'm not sure if that fix works. If you viewed a `.gradle.kts` file, I don't know if the syntax highlighting would try treat it as a Groovy or Kotlin file (especially with that `tm_scope: source.groovy.gradle` line).

**Comment by DecimalTurn** [comment]
If the goal is to remove the file from the stats bar, but keep the syntax highlighting as Kotlin, then it could be achieved with an  [override ](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) on a per-repo basis:
```
*.gradle.kts -linguist-detectable
```
I don't think there is a way to get that behavior by default.

**Comment by DecimalTurn** [comment]
...unless we added a new data-language associated with the extension `.gradle.kts`, but using Kotlin's syntax highlighting. However, that seems a bit overkill. Can the build code be specified in more languages than just Kotlin?

**Comment by mikewacker** [comment]
There's only two DSLs for Gradle: Groovy and Kotlin. The Groovy DSL has been around longer, but the Kotlin DSL recently became the default for new Gradle builds.

https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds

A new data language may be the best option here.

**Comment by DecimalTurn** [comment]
Well, there is [290k+](https://github.com/search?q=path%3A*.gradle.kts&type=code) file with the extension `*.gradle.kts`, so the popularity threshold isn't an issue if a new language needs to be added.

2 points needs to be clarifed however:
- What should the name of that language be?
- What color should be associated to it?

**Comment by mikewacker** [comment]
- "Gradle Kotlin DSL" (The old "Gradle" will really mean "Gradle Groovy DSL")
- I guess we could just reuse "#02303a"

**Comment by DecimalTurn** [comment]
Sounds good to me. Are you comfortable making a PR for this?

**Comment by mikewacker** [comment]
Did start looking at this, but I'm not sure what to do for `tm_scope` for the Kotlin DSL.

Took a look at https://github.com/ldaley/gradle.tmbundle/, which is where `source.groovy.gradle` is sourced from IIUC, and that project only seems to support the Groovy DSL.

**Comment by DecimalTurn** [comment]
If you want to have the same syntax highlighting as Kotlin, you'd need to use Kotlin's `tm_scope`.
