### ISSUE TITLE
Add Language: VisionScript

### ISSUE THREAD

**Issue by capjamesg** [github-linguist/linguist#6519]
## Language name

[VisionScript](https://visionscript.dev)

VisionScript is an abstract programming language for doing common computer vision tasks, fast.

The language is new and in an early stage of development. I want people to be able to make interesting, fun visual applications in a few minutes, without any programming experience. (You can make an app that counts how many people are in a room in ~5 lines of code!)

To that end, I'm working on different modalities of usage (i.e. via [Notebooks](https://visionscript.dev/), [paper-powered programming](https://visionscript.dev/paper/), and more) so that there are multiple entry paths for learning the language.

Inclusion in Linguist would be a boon to helping more advanced learners read VisionScript on GitHub.

## URL of example repository

- https://github.com/capjamesg/visionscript-examples

## URL of syntax highlighting grammar

- https://github.com/capjamesg/visionscript-textmate-grammar/blob/main/syntaxes/vic.tmLanguage.json

## Most popular extensions

VisionScript has two extensions:

- `.vic`: VisionScript programs.
- `.vicnb`: VisionScript Notebooks, for use in the Notebook programming environment.

## Detected language

To the extent I can see, GitHub does not identify `.vic` files as another programming language.

**Comment by johnmays** [comment]
I don't think it will be possible to add VisionScript for a while.  There is a language popularity requirement (#5756) which states that each extension has to have at least 2000 unique files on GitHub to be added.  Currently, it looks like:
-[`.vic` only has 171 files](https://github.com/search?q=path%3A*.vic+NOT+is%3Afork&type=code)
-[`.vicnb` has 0 files](https://github.com/search?q=path%3A*.vicnb+NOT+is%3Afork&type=code)

**Comment by capjamesg** [comment]
Thank you for the information! I will close this PR for now.
