### ISSUE TITLE
Issue with C syntax highlighter

### ISSUE THREAD

**Issue by VoltrexKeyva** [github-linguist/linguist#6528]
## Describe the bug

The C syntax highlighter hasn't been working properly for ~2-3 months or so now, a good amount of keywords aren't being highlighted or simply messing up.

The C TextMate grammar is [c.tmbundle](https://github.com/textmate/c.tmbundle) but it hasn't been changed in years yet the C syntax highlighter stopped working properly while the C++ syntax highlighter works just fine (both the C and C++ TextMate grammars are a part of c.tmbundle).

There's also no other TextMate grammar provided by vendors that uses the `c`, `cats`, `h`, or `idc` extensions that would conflict with c.tmbundle, so I don't see what could causing this to occur...

**Note:** this of course happens on both the website and GitHub Mobile.

C syntax highlighter ([file](https://github.com/libuv/libuv/blob/v1.x/src/idna.c)):
<img src="https://github.com/github-linguist/linguist/assets/62040526/0f45a89c-80ca-4b4e-8f33-939b512ab84d" width="300" height="600" />

C++ syntax highlighter ([file](https://github.com/nodejs/node/blob/main/src/cares_wrap.cc)):
<img src="https://github.com/github-linguist/linguist/assets/62040526/4f4da26c-4114-4227-8028-cd64b2e6ecbd" width="300" height="600" />

### Expected behaviour

For the keywords and such to highlight properly instead of just showing up as plain text.

**Comment by lildude** [comment]
GitHub doesn't use the TextMate grammar for C as denoted by the 🐌 emoji in the [README.md](https://github.com/github-linguist/linguist/tree/master/vendor).

As also [documented](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file), all grammar issues should be logged with the upstream grammars. If the upstream grammar doesn't exhibit this issue, please contact GitHub support to report the issue using the "Contact GitHub" link at the bottom of an affected page. They'll route the issue to the team that maintains the syntax highlighting engine and they'll look into pulling an update from the upstream grammar. Unfortunately we can't do it from here in Linguist.

Closing as this is not an issue with Linguist or within Linguist's control.
