### ISSUE TITLE
Support crontab syntax

### ISSUE THREAD

**Issue by haxwithaxe** [github-linguist/linguist#6547]
This is a super low priority for me. I just want crontab syntax highlighting in my README.md's on GitHub which claims to use this library. If that's true, then thank you. I'm very happy with your work. If not then this is just a common config/code format that you don't support yet.

## Language name
crontab

## URL of example repository
If you mean an example implementation of the syntax highlighting.
https://github.com/vim/vim/blob/6ffcc58be32aa1b337bc839cfe173b68cfde7085/runtime/syntax/crontab.vim
If you mean examples of crontab files I can provide those as needed. I didn't find any comprehensive examples in a moderately quick search.

## URL of syntax highlighting grammar
I'm not aware of a formal highlighting specification. Below are a couple example syntax highlighting implementations.
https://github.com/vim/vim/blob/6ffcc58be32aa1b337bc839cfe173b68cfde7085/runtime/syntax/crontab.vim
https://github.com/textmate/cron.tmbundle/blob/master/Syntaxes/Crontab.tmLanguage < I've never used this one but it's another example

## Most popular extensions
I don't know what is meant by this. I suspect that there are no extensions to the crontab format.

## Detected language
Crontab files are detected as the ``crontab`` filetype by vim/neovim.

**Comment by Alhadis** [comment]
> I don't know what is meant by this. I suspect that there are no extensions to the crontab format.

That section's referring to file extensions (as in, `.txt`, `.sh`, `.html`, etc). To my knowledge, crontab files don't use any particular filename suffix.

That TextMate grammar looks pretty good, BTW:

<img src="https://github.com/github-linguist/linguist/assets/2346707/c1e73d2e-8fb6-4572-b385-2e3832bb57cf" width="697" alt="Figure 1" />

**Comment by haxwithaxe** [comment]
Ah, yeah. I've never seen a crontab with a file extension. When you run `crontab -e` it creates a file named ``crontab`` in a temporary directory.
I prefer the vim version of the highlighting. It colorizes the columns which is handy in big crontabs.
