### ISSUE TITLE
Unmarking an attribute by prepending "-" doesn't work

### ISSUE THREAD

**Issue by SupaJoon** [github-linguist/linguist#6549]
## Describe the bug
The linguist [docs](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#detectable) shows that prepending the linguist attribute with "-" will unmark it but that doesn't work. In this [page](https://github.com/evergreen-ci/evergreen/compare/main...SupaJoon:linguist-test-1?expand=1) I would expect the hidden file to be visible.

### Expected behaviour
I would expect that prepending "-" would do the same thing as appending "=false" like in this [page](https://github.com/evergreen-ci/evergreen/compare/main...SupaJoon:linguist-test-2?expand=1).

**Comment by lildude** [comment]
It should and does definitely work. I notice your fork is really old and doesn't include the override. Do you still see the issue if you update you fork?

**Comment by lildude** [comment]
🤔 oh yes. This definitely used to work, we've made no changes in Linguist around this, and Linguist definitely acknowledges these the same:

```console
➜ ls -lR */package-lock.json
-rw-r--r--  1 lildude  staff  24 15 Sep 09:21 a/package-lock.json
-rw-r--r--  1 lildude  staff  24 15 Sep 09:21 b/package-lock.json
-rw-r--r--  1 lildude  staff  24 15 Sep 09:38 c/package-lock.json
➜ cat .gitattributes
a/package-lock.json -linguist-generated
b/package-lock.json linguist-generated=false
➜ github-linguist a/package-lock.json --json | jq
{
  "a/package-lock.json": {
    "lines": 3,
    "sloc": 3,
    "type": "Text",
    "mime_type": "application/json",
    "language": "JSON",
    "large": false,
    "generated": false, <----- cos of -linguist-generated
    "vendored": false
  }
}
➜ github-linguist b/package-lock.json --json | jq
{
  "b/package-lock.json": {
    "lines": 3,
    "sloc": 3,
    "type": "Text",
    "mime_type": "application/json",
    "language": "JSON",
    "large": false,
    "generated": false,  <----- cos of linguist-generated=false
    "vendored": false
  }
}
➜ github-linguist c/package-lock.json --json | jq
{
  "c/package-lock.json": {
    "lines": 3,
    "sloc": 3,
    "type": "Text",
    "mime_type": "application/json",
    "language": "JSON",
    "large": false,
    "generated": true,  <----- cos of no override
    "vendored": false
  }
}
➜ 
```

I suspect something has changed on the GitHub side. I'll do some more research and see what I can find.

**Comment by lildude** [comment]
Oh wow!!! I've just found the minus syntax has never worked in diffs on GitHub since Linguist introduced support for the minus syntax way back in 2020 in https://github.com/github-linguist/linguist/pull/4780. I've opened a PR to correct this. I'll close this issue once it's been deployed.

I feel really silly for continuously telling peeps this does work when it clearly doesn't 😊

**Comment by lildude** [comment]
Things should now be working and all looks good from your original link @SupaJoon
