### ISSUE TITLE
Change C#'s color to purple

### ISSUE THREAD

**Issue by xamir82** [github-linguist/linguist#6582]
In Linguist, C# is currently green (and [has been for years](https://github.com/github-linguist/linguist/pull/1524)). The [new logo](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)), however, is purple, along with the [new official VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), it has also [historically](https://www.google.com/search?sca_esv=573549883&sxsrf=AM9HkKmtrWM0xTdJpepR_vbi9KFmy_TnEg:1697347557531&q=c%23+logo&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj2jeixqPeBAxV9xAIHHbt-CfMQ0pQJegQIDBAB) been more associated with purple than green or any other color.

A purple-ish color makes increasingly more sense than green for C#, I would propose #5b37d6 as the color.

**Comment by lildude** [comment]
If you wish to change the colour, you need to gain wider community support on that language's public community forums (and reference it in the appropriate section of the PR template), not in this repo.

See https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#changing-the-color-associated-with-a-language for more details.

Closing as this is not the right place to garner support for a colour change.
