### ISSUE TITLE
Markdown: indented code blocks cause text to be marked as invalid.

### ISSUE THREAD

**Issue by MarkvanMents** [github-linguist/linguist#6587]
## Describe the bug
If I am viewing changes from commits for a markdown file, large amounts of text are marked invalid at the end of an indented code block. I believe the markdown is valid (the file is displayed correctly in a number of markdown editors) and the highlighting makes the code very difficult to read.

I have only noticed this happening for the last few months.

See example images below.
![265926031-5fb242fb-678b-4053-981c-a4c14bd83597](https://github.com/github-linguist/linguist/assets/35492184/fa6e9152-5e25-4eba-8ca7-85189c3cc724)

This is rendered (in GitHub) as

![265926982-c4a25c32-8ce2-438b-a992-bbc7a00bf118](https://github.com/github-linguist/linguist/assets/35492184/1be03f3e-af25-4458-af12-f24dc7621924)

which is what I wanted. So I can't see where the error is.

Here's a link to an example in my public repo. https://github.com/mendix/docs/commit/20b334e90d4f069326b4a1e4a51120801b900660#diff-fa4e89b8b6b7fca9589f44b77d58a53d33c15272a2853b46e55e86e0aee2e7f0R205

### Expected behaviour
There should be no highlighting for this syntax. If the indented code block ticks are a syntax error according to strict Markdown, then only the ticks should be highlighted. But I don't believe this should be highlighted at all.

### Related discussion
None that I have found.

### Additional notes
I've raised this with GitHub (https://github.com/orgs/community/discussions/66093), but I understand that here is a better place to report the problem.

**Comment by lildude** [comment]
> I've raised this with GitHub (https://github.com/orgs/community/discussions/66093), but I understand that here is a better place to report the problem.

Nearly. From our [troubleshooting doc](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](/vendor/README.md).
> 
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.**
Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

Closing as this will be an issue with the upstream grammar and not Linguist.
