### ISSUE TITLE
Better code examples for the Genero language

### ISSUE THREAD

**Issue by sebflaesch** [github-linguist/linguist#6628]
The existing code samples for the Genero language should be reviewed.
We can take care of this and make a pull request from the https://github.com/sebflaesch/linguist-genero fork.

**Comment by lildude** [comment]
> The existing code samples for the Genero language should be reviewed.

Why? We don't change samples unless they're blatantly wrong and have never been correct. Why? Because if they've been valid once before, there is almost certainly going to be code on GitHub using that old format/approach/whatever.

**Comment by lildude** [comment]
> I would expect that the "TextMate files" are THE reference to identify what a language syntax is, and I do not expect other tools to find out what syntax/keywords corresponds to a specific file extension...

These aren't used by linguist at all. They're purely collected for the highlighting engine which is a completely independent internal service and are only used once linguist has identified the language of the file. It's more efficient to collect these grammars when the language is added than attempting to maintain the things in two separate places. It's however not very efficient to use them for language detection.

**Comment by sebflaesch** [comment]
@lildude: I have reviewed my new "state of the art" samples, having only .4gl and .per files, respectively in TOP/samples/Genero and "TOP/samples/Genero Forms" directories.
Would that change be accepted by a pull request?

**Comment by lildude** [comment]
Oh, and you can update the samples and grammar in the same PR... we're not fussy about this sort of thing. We also squash commits on merge so don't care about the commit history so go wild.

**Comment by sebflaesch** [comment]
Thank you @lildude !
Finally I think you can close this issue as dup for #6629, we want to provide a single PR.

**Comment by lildude** [comment]
Changes have shipped. Closing.
