### ISSUE TITLE
TOML Trailing Comma bug

### ISSUE THREAD

**Issue by ddelange** [github-linguist/linguist#6636]
## Describe the bug

Hi :wave:

TOML allows trailing comma in inline arrays ref https://github.com/toml-lang/toml/issues/246#issuecomment-57919189.

Here's an example TOML where the trailing comma causes a bug (incorrect red highlight onwards): https://github.com/ddelange/mapply/blob/0.1.23/pyproject.toml#L60

```toml
[tool.ruff]
select = ["ALL"]
ignore = [
  "D107", # we have pydoclint with class docstring
  "D407", # we have google style docstrings
  "E501", # we have black
  "ANN", # we have mypy
  "TRY003", # there is EM102
  "D203", # there is D211
  "D213", # there is D212
  "FIX002", # there is TD002,TD003
]

[tool.ruff.extend-per-file-ignores]
"**/tests/**/*.py" = [
  "S101", # assert is fine in tests
  "D100", # tests is not a package
  "D104", # tests modules don't need docstrings
]
```

### Expected behaviour

Code following the inline array with trailing comma should not have red highlight.

**Comment by lildude** [comment]
As per the [troubleshooting](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file) doc, this is a problem with the upstream grammar. Please open an issue there.

**Comment by ahvigil** [comment]
is it possible the upstream grammar is being improperly applied somehow? The textmate toml bundle seems to parse fine in TextMate itself- but you can see even some of the [official toml spec test cases](https://github.com/toml-lang/toml-test/blob/master/tests/valid/spec-example-1.toml) show up with error highlights in the github rendering. 

I can't pin this down exactly but I don't remember toml files rendering this way in the past and neither the toml spec nor the upstream grammar have changed in years. I _feel_ like I would've noticed this in one of the [many pyproject.toml](https://github.com/pypa/pip/blob/main/pyproject.toml#L153-L171) files that now highlight in red. 🤷

**Comment by Alhadis** [comment]
@ahvigil This isn't the fault of the TextMate grammar. There appears to have been a change in GitHub's own PrettyLights highlighter; the grammar itself is valid and no changes to it are necessary. See https://github.com/github-linguist/linguist/pull/6603#issuecomment-1867175606 for more details.

**Comment by lildude** [comment]
I've opened https://github.com/github-linguist/linguist/issues/6668 to track the highlighting issues in one place

**Comment by jtbandes** [comment]
Also, for what it's worth I believe the issue here is triggered by the line comment, not the trailing comma. It looks fine if I remove the last comment in the `ignore` list:

```toml
[tool.ruff]
select = ["ALL"]
ignore = [
  "D107", # we have pydoclint with class docstring
  "D407", # we have google style docstrings
  "E501", # we have black
  "ANN", # we have mypy
  "TRY003", # there is EM102
  "D203", # there is D211
  "D213", # there is D212
  "FIX002   ---> comment removed here",
]

[tool.ruff.extend-per-file-ignores]
"**/tests/**/*.py" = [
  "S101", # assert is fine in tests
  "D100", # tests is not a package
  "D104", # tests modules don't need docstrings
]
```
