### ISSUE TITLE
.cdf Files in my Repo Misclassified as Mathematica

### ISSUE THREAD

**Issue by Psychpsyo** [github-linguist/linguist#6642]
In [my project](https://github.com/Psychpsyo/Cross-Universe-Online-Frontend), I am using ``.cdf`` as the file extension for a rather niche custom language.
According to the contributing guidelines here, this language is too niche to be included in linguist.
But it is being misclassified as Mathematica and [the troubleshooting guide](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md) says I should open an issue when this happens so I am opening this one to ask:
What should I do about this?
Am I supposed to use a custom override? (The [docs for overrides](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) say that would make it stop appearing in the language statistics which wouldn't be great)
Or are niche languages ok to be included for disambiguation if their extension is already included for another language?

**Comment by lildude** [comment]
> What should I do about this?

You will need to use an override to ignore the files or force the language to something like text.

We only accept changes related to languages which are popular enough for inclusion so changes for niche will not be accepted.

**Comment by Psychpsyo** [comment]
> You will need to use an override to ignore the files or force the language to something like text.

Alright, thanks.
