### ISSUE TITLE
Recognize `jq` scripts

### ISSUE THREAD

**Issue by mcandre** [github-linguist/linguist#6660]
## Describe the enhancement
Please highlight `*.jq` files and executables with `jq` hashbangs as JQ scripts.

Example:

https://github.com/mcandre/jelly/blob/main/example/jelly

**Comment by 2nine1e** [comment]
> 

> **.33.000033**

**Comment by 2nine1e** [comment]
my ride home

**Comment by lildude** [comment]
> with `jq` hashbangs as JQ scripts.

Your example doesn't have a `jq` hashbang 😉, it has a `/bin/sh` hashbang as it is rightly a shell script that is running the `jq` command. 

[This](https://github.com/omegat-org/omegat-user-support-archive/blob/0f73cef9b5928cf923ad5e4792b19d9e2e3f94d4/bin/json2txt#L4) on the other hand is an example which also illustrates that a) linguist already supports jq and b) one of the [override](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) methods you can use.

This is easy enough to add so feel free to submit a PR which adds an `interpreters` section to the current [jq entry](https://github.com/github-linguist/linguist/blob/559a6426942abcae16b6d6b328147476432bf6cb/lib/linguist/languages.yml#L8194).
