### ISSUE TITLE
C# template files incorrectly identified as pascal

### ISSUE THREAD

**Issue by vpenades** [github-linguist/linguist#6662]
## Describe the bug

C# nuget packages allow to include .cs files that can be templated:   the usual extension for this is .cs.pp , where .pp extension tells
nuget that it should treat the file as a .cs template.

### Expected behaviour

nuget .cs template files should be identified as C#

### Additional notes

See https://github.com/vpenades/CodeSugar

**Comment by lildude** [comment]
If usage is sufficiently high, feel free to submit a PR to add support for this extension to C#. See [CONTRIBUTING.md](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md) for details. Until then, you can use an [override](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) to force the language.

**Comment by Alamingazipur** [comment]
👍

alamin reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by DecimalTurn** [comment]
It seems like the extension `cs.pp` has already reached the popularity threshold to be added (3.3k files at the moment): 
https://github.com/search?q=path%3A*.cs.pp&type=code

@vpenades I can help with the PR creation to add `cs.pp` to the C# if you'd like. The details of how to do it are explained here: https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language
Note that you'll need is a sample file that is representative of cs.pp files (see step 2).

**Comment by vpenades** [comment]
As suggested by @lildude I was able to fix my repo with an override, so it's fine from my side

**Comment by DecimalTurn** [comment]
@vpenades The workaround using .gitattributes works for the stats bar, but not for search. See [here](https://github.com/search?q=repo%3Avpenades%2FCodeSugar%20path%3A*.cs.pp&type=code) for instance 
![image](https://github.com/github-linguist/linguist/assets/31558169/44866d18-5e34-4c87-87d1-5bc28068ae64)

Also, why not take this opportunity to fix this for everyone at the same time? Just let me know if you have a file that would be a good sample in your repo and I can make the PR.

**Comment by vpenades** [comment]
Oh, I thought you proposed me to make the PR, my hands are full with several projects.

You can pick any cs.pp from here:

https://github.com/vpenades/CodeSugar/tree/main/src/CodeSugar.System.IO.Sources

**Comment by DecimalTurn** [comment]
The issue can now be closed; PR has been merged and is now part of the latest release,
