### ISSUE TITLE
Remove language, not file extensions, from particular repos

### ISSUE THREAD

**Issue by sp-droid** [github-linguist/linguist#6706]
In the attributes file we can only specify which directories or extensions to remove from linguist's languages calculation. For example, remove all .ipynb files because in my opinion Jupyter notebooks is not a language and it isn't relevant. 

It would be nice to also have the possibility of removing a language from a repo, no matter the extension. For example remove Jupyter notebook language. Therefore in the calculation from every .ipynb file we ignore the Jupyter notebook contribution and only take into account the 16.67% something of Python contained in them.

"Just remove .ipynb files!" No, this destroys the statistics about Python.
I am very satisfied with linguist otherwise, it's an excellent tool to prove your experience but the Jupyter notebook issue has been bothering me for years.

**Comment by Alhadis** [comment]
What's wrong with simply excluding the language's extensions that're in-use by a project?

**Comment by sp-droid** [comment]
@Alhadis Usually this is enough. Exclude .html for HTML, .zig for Zig, .js for Python. With .ipynb there are two languages, 16.67% python + rest is Jupyter notebook. I don't want to exclude python, but I do want to exclude Jupyter notebook. I don't know if I'm making myself clear

**Comment by lildude** [comment]
> With .ipynb there are two languages, 16.67% python + rest is Jupyter notebook. I don't want to exclude python, but I do want to exclude Jupyter notebook.

🤔 Linguist doesn't do mixed language identification of file (see the many previous discussions about Jupyter and python) so a Jupyter file will always be identified as such unless you're using a non standard extension or an override. This means you'll never have a situation where a repo only containing Jupyter files is reporting both python and Jupyter so I'm struggling to understand when and why you'd want this functionality when you can already use an override to get your desired behaviour. 

If we implanted the exclusion of a language, your Jupyter files will not be associated with any language, which would be the same as implementing an override that sets the language to text.

**Comment by sp-droid** [comment]
I understand. I thought it was possible due to mistakenly assuming it from #3282 
Thanks, I'll close it
