### ISSUE TITLE
EJS grammar doesn't seem to work on GitHub

### ISSUE THREAD

**Issue by davidmurdoch** [github-linguist/linguist#6734]
## Describe the bug
I've set `app/*.html` to `linguist-language=EJS` in my `.gitattributes`, and GitHub's languages list detects it as such, but GitHub's UI doesn't highlight it correctly.

### Expected behavior
It should highlight the EJS and HTML correctly

.gitattributes:
https://github.com/davidmurdoch/metamask-extension/blob/dc9cdb222347a92b286959dd8b645d7c2c6cd386/.gitattributes#L20

Example Html File with incorrect highlighting:
https://github.com/davidmurdoch/metamask-extension/blob/dc9cdb222347a92b286959dd8b645d7c2c6cd386/app/home.html#L6-L10

---

This might be due to the referenced grammar repo not being updated in the last 13 years: https://github.com/github-linguist/linguist/blob/559a6426942abcae16b6d6b328147476432bf6cb/grammars.yml#L365-L366 => https://github.com/gregory-m/ejs-tmbundle/tree/5e48fff7258a94a8f57b142fa38571a1f9f68c44

Maybe https://github.com/Digitalbrainstem/ejs-grammar would work well (it works great in VSCode!)?

---

Edit: I just noticed that https://github.com/github-linguist/linguist/blob/master/vendor/README.md references https://github.com/tree-sitter/tree-sitter-embedded-template, not https://github.com/Digitalbrainstem/ejs-grammar . So I don't understand how anything works here. haha

**Comment by lildude** [comment]
Linguist is not responsible for syntax highlighting problems as stated in the [troubleshooting doc](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file); it only provides the grammars for the highlighting engine for most of the languages.

In this case, as you've pointed out, it doesn't. The EJS tree-sitter grammar is used and it's implemented directly by the highlighting engine. 

I recommend checking if this file highlights correctly in an editor that uses this grammar. Something like Neovim might. If it doesn't, you need to raise an issue with the grammar. If it does, you need to contact GitHub support using the "Contact GitHub" link at the bottom of any page on the site and they can pass the issue onto the team that maintains the highlighting engine.

Closing as this is not a problem with linguist.
