### ISSUE TITLE
Some PowerShell variables aren't highlighted (`$Error`, `$PSVersionTable`)

### ISSUE THREAD

**Issue by o-l-a-v** [github-linguist/linguist#6757]
## Describe the bug

Some PowerShell variables aren't highlighted.

The following:

````markdown
```powershell
$SomeVariable
$Error
$PSVersionTable
```
````

Results in:

<img width="105" alt="image" src="https://github.com/github-linguist/linguist/assets/6450056/83a29daa-cd14-43af-b7f7-da9ca344ec34">

Related issue:

* <https://github.com/PowerShell/vscode-powershell/issues/4944>

### Expected behaviour

All variables should be highlighted, like highlight.js does it <https://highlightjs.org/demo>:

![image](https://github.com/github-linguist/linguist/assets/6450056/e9a02527-325d-4510-a40a-a2cd0da05747)

**Comment by lildude** [comment]
This is a problem with the upstream grammar, not linguist. Please open an issue in the grammar repo.

**Comment by o-l-a-v** [comment]
That would be <https://github.com/PowerShell/EditorSyntax>, correct? I'll make an issue there if it doesn't exist already.

**Comment by lildude** [comment]
Yup, [that’s grammar](https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/vendor/README.md?plain=1#L435) we use. Interesting that the VSCode grammar suffers from the same issue.
