### ISSUE TITLE
Nushell has 2 different grammars

### ISSUE THREAD

**Issue by texastoland** [github-linguist/linguist#6762]
## Describe the bug

See:
https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/grammars.yml#L861-L864

Using `nushell` (preferred highlighter):

```nushell
export def --env main [
  field: cell-path # The environment variable name or nested option cell path
  value: any # The value to set or append
  --append (-a) # Append to the previous value or wrap in a new list
]: nothing -> nothing {
  def 'get or' [default field] {
    get --ignore-errors $field | default $default
  }
  let value = if $append {
    $env | get or [] $field | append $value
  } else {
    $value
  }
  let field = $field | to text | split row .
  let value = match $field {
    [_] => $value
    [$root, ..$field] => {
      let field = $field | into cell-path
      $env | get or {} $root | upsert $field $value
    }
  }
  load-env { ($field | first): $value }
}
```

Using `nu`:

```nu
export def --env main [
  field: cell-path # The environment variable name or nested option cell path
  value: any # The value to set or append
  --append (-a) # Append to the previous value or wrap in a new list
]: nothing -> nothing {
  def 'get or' [default field] {
    get --ignore-errors $field | default $default
  }
  let value = if $append {
    $env | get or [] $field | append $value
  } else {
    $value
  }
  let field = $field | to text | split row .
  let value = match $field {
    [_] => $value
    [$root, ..$field] => {
      let field = $field | into cell-path
      $env | get or {} $root | upsert $field $value
    }
  }
  load-env { ($field | first): $value }
}
```

### Expected behaviour

Identical rendering.

**Comment by ysthakur** [comment]
This may be because of the other Nu language: https://github.com/programming-nu/nu

**Comment by texastoland** [comment]
You're right great sleuthing!

**Comment by Alhadis** [comment]
> Looks like the [grammar for Nu](https://github.com/jsallis/nu.tmbundle/tree/7beffd8cfc2542b43ebfabd66998d0fd503d1bb0) is unmaintained.

There's an official fork of this grammar, which is now being maintained by the @programming-nu org itself. See [`programming-nu/nu.tmbundle`](https://github.com/programming-nu/nu.tmbundle).

**Comment by texastoland** [comment]
Sounds like they need to PR here ✅
https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/.gitmodules#L923-L925

**Comment by Alhadis** [comment]
> (but it's also dormant since 5 years)

Well… Nu is a dialect of Lisp (Syntactically, Lisp is pretty straightforward (which is why we love it (and why I'm already three levels deep into parentheses (because (lisp))))).

> Looks based on Objective-C which has been unused since Swift.

Unused? Erh, no, Objective-C is still supported…

**Comment by texastoland** [comment]
If you're here defending Nu that seems like more than enough reason for GitHub to keep it around 💯

**Comment by Alhadis** [comment]
@texastoland We don't remove support for languages once they're added. Sure, they might fall into disuse (many languages do), but that doesn't change the fact that they *were* popular once, and there are no doubt countless archived or unmaintained projects written in that language distributed throughout GitHub.

I mean, we still support ActionScript 3, so… 😉

**Comment by texastoland** [comment]
No doubt. Before you chimed in I was going to ask about metrics. AFAICT your heuristics are working regardless ✅
https://github.com/search?q=language:nu&type=repositories

**Comment by texastoland** [comment]
Would there be any way to prioritize Nushell (if there's more of it)?

**Comment by Alhadis** [comment]
> The XY problem on our Discord server

Erh, what do you mean…?

**Comment by texastoland** [comment]
Sorry for being unclear. I mean occasionally people ask about misclassification. I haven't seen it on the repo level (like nu_scripts above) but only 7 random dotfiles repo populate in that GitHub query. Do you know of anything we can do on our end to change that? Thanks for your time on a Sunday 🙊

**Comment by Alhadis** [comment]
LOL, yeah, it's almost midday here in Melbourne. 😁

I think the confusion stems from two different types of code search:

<table>
	<thead>
		<tr>
			<th>Search type</th>
			<th>Description</th>
			<th>Operator</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th scope="row">Repository search</th>
			<td>Only lists repositories that're <em>predominantly</em> NuShell</td>
			<td><code><a href="https://github.com/search?q=language:nushell&type=repositories">type=repositories</a></code></td>
		</tr>
		<tr>
			<th scope="row">File search</th>
			<td>Lists individual files identified as NuShell</td>
			<td><code><a href="https://github.com/search?q=language%3Anushell&type=code">type=code</a></code></td>
		</tr>
	</tbody>
</table>

**Comment by texastoland** [comment]
> [github.com/search?q=language:nushell&type=repositories](https://github.com/search?q=language:nushell&type=repositories)

Is this a repository or file search? nu_scripts (and much of the ecosystem) is 98% Nushell on the repo page.

**Comment by Alhadis** [comment]
> But nu_scripts is 99.7% Nushell and not found above (or any other Nushell library).

🤔 Okay, yeah, that's weird. That shouldn't be happening… I'm wondering if there's an indexing issue on GitHub's end. @lildude will be able to elucidate.

**Comment by texastoland** [comment]
Thanks for checking regardless 🙌🏼
