### ISSUE TITLE
Templ Templating Lanuage

### ISSUE THREAD

**Issue by tris203** [github-linguist/linguist#6777]
[## Language name
Templ ( A popular Go Templating library) 

[Repo Link](https://github.com/a-h/templ)

## URL of example repository
https://github.com/a-h/templ/tree/main/examples

## URL of syntax highlighting grammar
[Tree Sitter](https://github.com/vrischmann/tree-sitter-templ)
[VsCode](https://github.com/templ-go/templ-vscode/tree/main/syntaxes)

## Most popular extensions

.templ

## Detected language

none

Currenly approx 7k files
https://github.com/search?q=path%3A%2F.%2B%5C.templ%24%2F++package+templ&type=code

Code can be identified by the go style `package mod` import

**Comment by luisnquin** [comment]
I think it should be "Templ" for consistency with other languages.

**Comment by luisnquin** [comment]
I guess this is just subjective, in 5 projects that I have with temp, it's the only highlighted language that is not in uppercase or sentence case.

### Example

![image](https://github.com/github-linguist/linguist/assets/86449787/91d5f03a-4ba2-4f54-857f-d56ae4957644)

But it's okay to follow their conventions, I thought it was something to fix
