### ISSUE TITLE
Add support for .containerfile extension

### ISSUE THREAD

**Issue by gnat** [github-linguist/linguist#6799]
`Containerfile` is currently an alias for `Dockerfile` great!

`blah.Dockerfile` works but `blah.Containerfile` does not.

**Comment by lildude** [comment]
If the extension is popular enough to meet our usage requirements, feel free to submit a PR to add support. You can find details in the CONTRIBUTING.md file.

**Comment by gnat** [comment]
Linguist already supports Containerfile as an alias of Dockerfile :eyes:

Containerfile is just the [standard OCI name](https://en.wikipedia.org/wiki/Open_Container_Initiative)

**Comment by lildude** [comment]
Indeed. But it's not going to magically appear in the `languages.yml` file without a PR, and support won't be added until usage meets our requirements. This applies to _all_ additions for new and existing languages.
