### ISSUE TITLE
Add Horse64

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6834]
## Language name
Horse64

## URL of example repository
https://codeberg.org/Horse64/core.horse64.org
https://codeberg.org/Horse64/hvm.horse64.org
https://codeberg.org/Horse64/horp.horse64.org
https://github.com/Gwion/gwion-benchmark

## URL of syntax highlighting grammar
Uhhhhhhh... You can probably find what you want [here](https://horse64.org/)... somewhere.

## Most popular extensions
.h64

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with only two users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
