### ISSUE TITLE
Add Formcore

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6836]
## Language name
Formcore

## URL of example repository
https://github.com/HigherOrderCO/FormCoreJS/blob/master/example.fmc

## URL of syntax highlighting grammar
https://github.com/HigherOrderCO/FormCoreJS/blob/master/example.fmc

## Most popular extensions
.fmc

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
