### ISSUE TITLE
Add Kind

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6837]
## Language name
Kind

## URL of example repository
https://github.com/HigherOrderCO/Kind-Legacy
https://github.com/HigherOrderCO/Kind1
https://github.com/HigherOrderCO/Kindex

## URL of syntax highlighting grammar
https://github.com/HigherOrderCO/Kind-Legacy/blob/master/SYNTAX.md
https://github.com/HigherOrderCO/Kind1/blob/master/SYNTAX.md

## Most popular extensions
.kind
.kind2

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
