### ISSUE TITLE
Add Interaction Calculus

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6838]
## Language name
Interaction Calculus

## URL of example repository
https://github.com/VictorTaelin/Interaction-Calculus/blob/master/example.ic

## URL of syntax highlighting grammar
https://github.com/VictorTaelin/Interaction-Calculus?tab=readme-ov-file#language

## Most popular extensions
.ic

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
