### ISSUE TITLE
Add HVM

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6839]
## Language name
HVM

## URL of example repository
https://github.com/HigherOrderCO/HVM
https://github.com/HigherOrderCO/HVM1
https://github.com/zicklag/hop
https://github.com/VictorTaelin/HOC
https://github.com/aripiprazole/trazodone
https://github.com/HigherOrderCO/Kind1/blob/master/crates/kind-checker/src/checker.hvm

## URL of syntax highlighting grammar
https://github.com/HigherOrderCO/HVM/tree/main/paper

## Most popular extensions
.hvm

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
