### ISSUE TITLE
Add Flufflepuff

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6841]
## Language name
Flufflepuff

## URL of example repository
https://github.com/juju2143/flufflepuff/blob/master/hello.fp

## URL of syntax highlighting grammar
https://github.com/juju2143/flufflepuff/blob/master/flufflepuff.l
https://github.com/juju2143/flufflepuff/tree/master?tab=readme-ov-file#conversion-table

## Most popular extensions
.fp

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
