### ISSUE TITLE
Add KeK

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6842]
## Language name
KeK

## URL of example repository
https://github.com/merskip/kek-language

## URL of syntax highlighting grammar
https://github.com/merskip/kek-language/blob/master/grammar.md

## Most popular extensions
.kek

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
