### ISSUE TITLE
Add Vyse

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6845]
## Language name
Vyse

## URL of example repository
https://github.com/srijan-paul/snap
https://github.com/Gwion/gwion-benchmark

## URL of syntax highlighting grammar
https://injuly.in/vyse/book/lang-basics/syntax.html

## Most popular extensions
.vy

## Detected language
Vyper

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
