### ISSUE TITLE
Add Kuroko

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6846]
## Language name
Kuroko

## URL of example repository
https://github.com/kuroko-lang/kuroko

## URL of syntax highlighting grammar
https://kuroko-lang.github.io/

## Most popular extensions
.krk

## Detected language
https://github.com/Gwion/gwion-benchmark

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
