### ISSUE TITLE
Add Pa

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6847]
## Language name
Pa

## URL of example repository
https://github.com/valkarias/Pa
https://github.com/Gwion/gwion-benchmark

## URL of syntax highlighting grammar
https://valkarias.github.io/contents/toc.html

## Most popular extensions
.pc

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
