### ISSUE TITLE
Спам

### ISSUE THREAD

**Issue by Astra4587** [github-linguist/linguist#6851]
### Additional notes
 Альхадиса закрыл не верно. Спам. Заблокировать комментарий.
![generated_image_ba130e73f73511ee8c16b2803b23326e](https://github.com/github-linguist/linguist/assets/167037619/11600b4c-fa87-47d6-a46e-
37db639f7b27)
Владелец разработчик Astra 4587. diff

**Comment by Alhadis** [comment]
No, I didn't <q lang="ru"><i>закры не верно</i></q>. You submitted a [gibberish pull-request](https://github.com/github-linguist/linguist/pull/6850/files) that makes as much sense in Russian as it does in English.

I'm not sure what you're trying to do, but whatever it is, you're in the wrong place. See [Linguist's readme](https://github.com/github-linguist/linguist?tab=readme-ov-file#documentation) for an overview of what this project does. Bear in mind that the software deals with <strong>programming</strong> languages (C, Java, Python), <em>not</em> natural (human) languages (English, Русский, German).

Note that if you continue to submit spam here, you _will_ be reported for abuse.
