### ISSUE TITLE
Add Bosque

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6854]
## Language name
Bosque

## URL of example repository
https://github.com/BosqueLanguage

## URL of syntax highlighting grammar
https://github.com/BosqueLanguage/bosque-language-tools/blob/main/syntaxes/bosque.tmLanguage.json

## Most popular extensions
.bsq

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
