### ISSUE TITLE
Add language: Blazor

### ISSUE THREAD

**Issue by andreadottor** [github-linguist/linguist#6883]
## Language name

Blazor

## URL of example repository

https://github.com/andreadottor/Umarell-BlazorWebApp
https://github.com/dotnet/blazor-samples

## Most popular extensions

.razor

## Detected language

JavaScript or HTML

**Comment by lildude** [comment]
In that case, Linguist already supports it:

https://github.com/github-linguist/linguist/blob/39fd5e93de98de3434cb3e857c5b1972c418f8c5/lib/linguist/languages.yml#L2821-L2834 so nothing more to do as we don't add support for frameworks.

**Comment by andreadottor** [comment]
@heIgee yep, and in this case we can include also the files with .cshtml extension, that use Razor Engine.

**Comment by heIgee** [comment]
> In that case, Linguist already supports it:
> 
> https://github.com/github-linguist/linguist/blob/39fd5e93de98de3434cb3e857c5b1972c418f8c5/lib/linguist/languages.yml#L2821-L2834 so nothing more to do as we don't add support for frameworks.

The problem is that linguist considers it  HTML. I don't find it fair, since Razor files can contain more C# than actual markup. Similar EJS, for example, is treated as a separate language
