### ISSUE TITLE
vCard (`.VCF`)

### ISSUE THREAD

**Issue by RokeJulianLockhart** [github-linguist/linguist#6888]
## Language name

vCard

## URL of example repository

https://github.com/search?q=repo%3AFolkerKinzel%2FVCards+path%3A*.vcf&type=code or https://github.com/kewisch/ical.js/blob/a981f07851f0470f9014710b1d66d82859506f7b/test/parser/vcard.vcf#L1-L34

## URL of syntax highlighting grammar

https://github.com/fox-projects/vscode-assorted-languages/blob/a7e1b5ae1b2c861e68e736cb0e83b451ae9a39b8/syntaxes/vcard.tmLanguage.json#L1-L79

## Most popular extensions

https://github.com/fox-projects/vscode-assorted-languages/blob/2e11eda0254def6d2a38a4873ae4c71650cc36cb/README.md#usage

## Detected language

Seemingly `text/plain`.

**Comment by DecimalTurn** [comment]
There seems to be 2 data formats using the `.vcf` extension:

* vCard with a similar syntax to [iCalendar](https://github.com/github-linguist/linguist/issues/6910).
* Variant Call Format (VCF) which is a tab-delimited textual format ([source](https://github.com/vcflib/vcflib/tree/382ae661fa19cfde6de56a8b3d7109d542373345?tab=readme-ov-file#overview)), ie. Tab Seperated Values (TSV).

In both cases, they have enough entries to be added to Linguist:
* [.vcf files for vCard](https://github.com/search?q=path%3A*.vcf+%22vCard%22+NOT+is%3Afork&type=code): 11k+ files.
* [.vcf files with TSV data](https://github.com/search?q=path%3A*.vcf+%22%23%23fileformat%22+NOT+is%3Afork&type=code): 70k+ files.

**Comment by DecimalTurn** [comment]
@Alhadis, it seems that Variant Call Format files use 2 `#` to indicate metadata at the top of the file and a single `#` to indicate the column headers. Do you think that would justify treating it seperatly from regular TSV data or we could simply add .vcf to the extensions associated to TSV? 

Related PR: https://github.com/github-linguist/linguist/pull/4959

```TSV
##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=a,length=630>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	b
a	281	>1>9	AGCCGGGGCAGAAAGTTCTTCCTTGAATGTGGTCATCTGCATTTCAGCTCAGGAATCCTGCAAAAGACAG	CTGTCTTTTGCAGGATTCCTGTGCTGAAATGCAGATGACCGCATTCAAGGAAGAACTATCTGCCCCGGCT	60.0	.	AC=1;AF=1;AN=1;AT=>1>2>3>4>5>6>7>8>9,>1<8>10<6>11<4>12<2>9;NS=1;LV=0	GT	1
```
[sample source](https://github.com/vcflib/vcflib/blob/382ae661fa19cfde6de56a8b3d7109d542373345/samples/z.vcf)

**Comment by lildude** [comment]
I'd suggest adding it to TSV unless it has a unique syntax that necessitates a different grammar for highlighting.
