### ISSUE TITLE
Strela

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6898]
## Language name
Strela

## URL of example repository
https://github.com/sunverwerth/strela

## URL of syntax highlighting grammar
https://github.com/sunverwerth/strela/blob/master/docs/syntax.md

## Most popular extensions
.strela

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
