### ISSUE TITLE
Eve

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6901]
## Language name
Eve

## URL of example repository
https://github.com/witheve/eve-starter

## URL of syntax highlighting grammar
https://witheve.github.io/assets/docs/SyntaxReference.pdf

## Most popular extensions
.eve

## Detected language

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
