### ISSUE TITLE
Add B4X

### ISSUE THREAD

**Issue by DecimalTurn** [github-linguist/linguist#6944]
## Language name

B4X
* [Website](https://www.b4x.com/)
* [Wikipedia page](https://en.wikipedia.org/wiki/B4X)

## URL of example repository

https://github.com/AnywhereSoftware/B4X-Pleroma

## URL of syntax highlighting grammar

NA

## Most popular extensions

* [.bas](https://github.com/search?q=path%3A*.bas+%2FB4%28J%7CA%7CR%29%3Dtrue%2F+NOT+user%3AAnywhereSoftware&type=code): 2.5+ files.

## Detected language

Usually Visual Basic 6.0 or BASIC

**Comment by DecimalTurn** [comment]
@AnywhereSoftware, can you confirm that there is no TextMate compatible syntax highlighting grammar for B4X? I couldn't find any, but maybe you have one available somewhere.

**Comment by AnywhereSoftware** [comment]
Hi,

I’m not familiar with such resource.

There is a prism based grammar: https://www.b4x.com/android/forum/threads/%F0%9F%90%A2-%F0%9F%91%A9%E2%80%8D%F0%9F%8F%AB-%F0%9F%91%A8%E2%80%8D%F0%9F%8F%AB-highlighting-b4x-code-in-html-pages-using-prism.117448/#content

 

Best regards, 

Erel Uziel

Anywhere Software

**Comment by DecimalTurn** [comment]
Thanks @AnywhereSoftware, a prism grammar is a good starting point, but it would need to be converted to the TextMate format and hosted on GitHub to be used as a grammar for syntax highlighting on GitHub.

Another possibility, in the meantime, would be to use VBA or VB.NET's grammar which are similar and already available. If you'd be OK with using one of these, let me know which one you prefer and I can go forward with a PR to add B4X.

Here's a demo of how it would look like (you'll need to view this on GitHub directly and not just on you email client I'm assuming).

Using [this file](https://github.com/jakebullet70/OctoTouchController/blob/fcf32317a311cb3abb0dcfad4dd34e5ec23edf1b/src/main/startAtBoot.bas).

Using VBA's syntax highlighting:

```vba

B4A=true
Group=MAIN
ModulesStructureVersion=1
Type=Service
Version=11.8
@EndOfDesignText@
#Region  Service Attributes 
	#StartAtBoot: True	
#End Region

Sub Process_Globals
	'These global variables will be declared once when the application starts.
	'These variables can be accessed from all modules.
	'---
	Private AutoStartBeenChecked As Boolean = False
	Private xui As XUI
End Sub

Sub Service_Create
End Sub

Sub Service_Start (StartingIntent As Intent)
	Log("Service_Start - startAtBoot")
	If AutoStartBeenChecked = False Then
		AutoStartBeenChecked = True
		If ( File.Exists(xui.DefaultFolder,"autostart.bin") ) Then
			StartApp
		End If
	End If
	Service.StopAutomaticForeground 'Call this when the background task completes (if there is one)
	StopService(Me) '--- above line replaces this
End Sub

Sub Service_Destroy
End Sub


Private Sub StartApp()
	Dim Intent1 As Intent
	Dim pm As PackageManager
	#if klipper
	Intent1 = pm.GetApplicationIntent("sadLogic.KlipperTouchController")
	#else
	Intent1 = pm.GetApplicationIntent("sadLogic.OctoTouchController")
	#End If
	StartActivity(Intent1)
End Sub

```

Using VB.NET's syntax highlighthing:

```vbnet

B4A=true
Group=MAIN
ModulesStructureVersion=1
Type=Service
Version=11.8
@EndOfDesignText@
#Region  Service Attributes 
	#StartAtBoot: True	
#End Region

Sub Process_Globals
	'These global variables will be declared once when the application starts.
	'These variables can be accessed from all modules.
	'---
	Private AutoStartBeenChecked As Boolean = False
	Private xui As XUI
End Sub

Sub Service_Create
End Sub

Sub Service_Start (StartingIntent As Intent)
	Log("Service_Start - startAtBoot")
	If AutoStartBeenChecked = False Then
		AutoStartBeenChecked = True
		If ( File.Exists(xui.DefaultFolder,"autostart.bin") ) Then
			StartApp
		End If
	End If
	Service.StopAutomaticForeground 'Call this when the background task completes (if there is one)
	StopService(Me) '--- above line replaces this
End Sub

Sub Service_Destroy
End Sub


Private Sub StartApp()
	Dim Intent1 As Intent
	Dim pm As PackageManager
	#if klipper
	Intent1 = pm.GetApplicationIntent("sadLogic.KlipperTouchController")
	#else
	Intent1 = pm.GetApplicationIntent("sadLogic.OctoTouchController")
	#End If
	StartActivity(Intent1)
End Sub

```

**Comment by AnywhereSoftware** [comment]
Hi,

The VBA grammar looks fine. Thank you for pushing this.

 

Best regards, 

Erel Uziel

Anywhere Software
