### ISSUE TITLE
Add Unison language

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6945]
## Language name
Unison

## URL of example repository
https://github.com/unisonweb/unison/tree/trunk/unison-src

## URL of syntax highlighting grammar
https://github.com/unisonweb/unison/tree/trunk/unison-syntax

## Most popular extensions
.u (May cause false positives with Unreal Engine repos.)
.uu
.cable

## Detected language

**Comment by lildude** [comment]
Dupe of https://github.com/github-linguist/linguist/issues/6909
