### ISSUE TITLE
Add Skript, a language that allows Minecraft server owners to configure their server.

### ISSUE THREAD

**Issue by HyperDondon** [github-linguist/linguist#6952]
## Language name
Skript

## URL of example repository
https://github.com/HyperDondon/BlissSMPSkriptV3
https://github.com/SkriptLang/Skript/tree/master/src/main/resources/scripts/-examples

## URL of syntax highlighting grammar
https://github.com/SkriptLang/skript-grammar

## Most popular extensions
https://marketplace.visualstudio.com/items?itemName=ayhamalali.Sk-VSC
https://marketplace.visualstudio.com/items?itemName=JohnHeikens.intelliskript

## Detected language
Skript

**Comment by lildude** [comment]
https://github.com/github-linguist/linguist/pull/6559
