### ISSUE TITLE
zetavm

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6955]
## Language name
zetavm

## URL of example repository
https://github.com/zetavm/zetavm

## URL of syntax highlighting grammar
https://github.com/zetavm/zetavm/blob/master/docs/design.md

## Most popular extensions
.pls

## Detected language
PLSQL

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
