### ISSUE TITLE
Never

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6963]
## Language name
Never

## URL of example repository
https://github.com/never-lang/never

## URL of syntax highlighting grammar
https://never-lang.readthedocs.io/en/latest/#syntax-level

## Most popular extensions
.nev

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666
