### ISSUE TITLE
Cobra

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6992]
## Language name
Cobra

## URL of example repository
https://github.com/search?q=Path%3A*.cobra&type=code

## URL of syntax highlighting grammar
http://cobra-language.com

## Most popular extensions
.cobra

## Detected language

**Comment by lildude** [comment]
This is too vague. The website doesn't load and there adores to be free different syntaxes using this extension, none of which are close to meeting our requirements. Closing but feel free to opened a new issue with more specific details.
