### ISSUE TITLE
Add vimscript and vim script as names of vim's scripting language

### ISSUE THREAD

**Issue by jmdevin** [github-linguist/linguist#7005]
#2752 was opened a while ago; long ago enough that it seemingly was forgotten in #3278. I'm wondering if it would now be possible to add both `vimscript` and `vim script` as names for vim's language?

**Comment by Alhadis** [comment]
Where are you seeing the old name? `VimL` <em>was</em> [renamed](https://github.com/github-linguist/linguist/commit/d8b91bd5c#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8R4454) to `Vim script` in #3278.

**Comment by jmdevin** [comment]
Whoops, I only saw that using 'vimscript' in a fenced code blocks doesn't work; after I found the issue I clicked through and read the repo as it existed at the time.

Would it still be possible to add vimscript as an alias, so it works without the space?

**Comment by jmdevin** [comment]
I'm certainly learning more about this then I thought I would.

> " Fuck spaces

Indeed.
