### ISSUE TITLE
Allow ssh and sshconfig tags for ssh config syntax highlighting.

### ISSUE THREAD

**Issue by coolaj86** [github-linguist/linguist#7041]
## Describe the enhancement

Support `` ```sshconfig ``, `` ```ssh ``, and `` ```ssh-config `` tags for _sshconfig_ highlight blocks.

### Support in the Wild

At the time of the previous issue discussion ssh config (<https://github.com/github-linguist/linguist/issues/3450>), the `Include` directive for ssh config was not well known, nor widely adopted.

However, now it is supported in macOS, Ubuntu, and many other Linuxes (anything with OpenSSH 8.x or higher): https://man.openbsd.org/ssh_config.5

Although the `Include` directive does not specify which extension should be used, `.ssh` and `.sshconfig` seem to be the common extensions, when one is used. `vim` also names its syntax highlighting `sshconfig`.

Specifically, `.ssh-config` is _NOT_ a common extention and `ssh-config` is not a common name for the syntax - at least not as far as I can tell.

As can be seen in <https://github.com/github-linguist/linguist/issues/3450#issuecomment-566368051>, currently only `` ```ssh-config `` is supported by GitHub.

### Recommendations

I'm recommending that `sshconfig`, in particular, be added for syntax highlighting as it seems to be the de facto naming convention.

I'd also recommend `ssh` because it's the most intuitive - and I highly, _highly_ doubt that there will be some sort of OpenSSH DSL script that would need the `ssh` tag in the future. That said, I do understand that, categorically, `ssh` might _feel_ wrong as it would seem to describe an ssh DSL rather than a config format. However, since the layperson would reasonably assume that `ssh` is the syntax and probably isn't aware that `sshconfig` is the de facto name for the syntax.

On another note, I would argue against `ssh_config` as the tag as that seems to defy the tag convention, and refers specifically to the file naming convention used for substituting the `/` in `~/.ssh/config` and the suggested system-wide configuration file name `/etc/ssh/ssh_config`, not the syntax itself.

**Comment by lildude** [comment]
We'd certainly accept a PR if you've got the time 😉

**Comment by coolaj86** [comment]
I'm not familiar with how the repo is laid out, but a brief search for `ssh-config` lead me to https://github.com/github-linguist/linguist/blob/f0aebbe90d3b9b9bae5b7258f99370def1ee489f/lib/linguist/languages.yml#L6522

According to that, I would think `` ```sshconfig `` _should_ work.

Perhaps the previous test was rendered years ago, made inactive, and never re-rendered. I'll try again now:

```sshconfig
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

```ssh-config
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

```ssh_config
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

```sshdconfig
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

```sshd-config
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

```sshd_config
Host my-nickname
  Hostname my-nickname.example.com
  User me
```

**Comment by coolaj86** [comment]
@lildude Can you direct me as to what I should be looking for? The thing that seemed the obvious thing either isn't applied to the deployed GitHub editor at large, or is a red herring.

**Comment by lildude** [comment]
If you're wanting to use the various other forms, you should add an `aliases` entry to the section you found in the `languages.yml` file. You can find other uses elsewhere in the file.
