### ISSUE TITLE
It cannot run in the KIWI browser

### ISSUE THREAD

**Issue by XM-8JD2** [github-linguist/linguist#7054]
## Describe the bug

Running linguist shows the following:
<img src="https://github.com/user-attachments/assets/11b91017-8ada-473c-a2d3-1bed9282d648" width="300px" />

If I click on "Settings," it shows the following(Rotate, and infinite loop):
<img src="https://github.com/user-attachments/assets/d7c1f67b-62fe-4d22-ba9d-5f065d70c2ce" width="300px" />

### Related discussion

I have already submitted an issue on their project: https://github.com/kiwibrowser/src.next/issues/1187

**Comment by lildude** [comment]
Linguist is for detecting programming languages on GitHub and not spoken languages. It is also written in Ruby so will not work with a project like Kiwi. Closing as invalid.

**Comment by XM-8JD2** [comment]
Sorry, it's my fault
