### ISSUE TITLE
C++20 keyword 'requires' not highlighted in syntax highlighting

### ISSUE THREAD

**Issue by dakka** [github-linguist/linguist#7093]
## Description
C++20 keyword "requires" not rendered in syntax highlighting.

## Steps to Reproduce: 
```C++
template <typename T>
requires std::is_integral_v<T>
void foo(T) {}
```

### Expected behaviour
'requires' keyword should be hilit

**Comment by lildude** [comment]
From the [troubleshooting.md doc](https://github.com/github-linguist/linguist/blob/main/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> ## There's a problem with the syntax highlighting of a file
>
> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](/vendor/README.md).
>
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.**
Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

**Comment by dakka** [comment]
Your submodule link 404s.

**Comment by lildude** [comment]
Whoops. It doesn't in the doc I quoted it from. Should take you to [README.md](https://github.com/github-linguist/linguist/blob/main/vendor/README.md).

Looks like this is a known issue already too: https://github.com/textmate/c.tmbundle/issues/68

This also appears to be a stale grammar so I doubt it'll be implanted anytime soon. If you know of a better grammar that works and is maintained, feel free to submit a PR to change the grammar.
