### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by MC-datapack** [github-linguist/linguist#7102]
## Language name
Json

## URL of example repository
https://github.com/MC-datapack/Extended-World-Height/tree/512/data/minecraft/dimension_type

## URL of syntax highlighting grammar
N/A

## Most popular extensions
`.json`
<!--

**Comment by lildude** [comment]
Linguist already has support for JSON but as it's considered data, it doesn't appear in the sidebar stats by default.

If you want it to appear, use an [override](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md).
