### ISSUE TITLE
Typst grammar not accessible

### ISSUE THREAD

**Issue by lildude** [github-linguist/linguist#7145]
Tests are failing because the typst grammar can't be found:

```
Error updating vendor/grammars/typst-grammar
Cloning into '/home/runner/work/linguist/linguist/vendor/grammars/typst-grammar'...
fatal: could not read Username for 'https://github.com/': No such device or address
fatal: clone of 'https://github.com/michidk/typst-grammar.git' into submodule path '/home/runner/work/linguist/linguist/vendor/grammars/typst-grammar' failed
Failed to clone 'vendor/grammars/typst-grammar'. Retry scheduled
Cloning into '/home/runner/work/linguist/linguist/vendor/grammars/typst-grammar'...
fatal: could not read Username for 'https://github.com/': No such device or address
fatal: clone of 'https://github.com/michidk/typst-grammar.git' into submodule path '/home/runner/work/linguist/linguist/vendor/grammars/typst-grammar' failed
Failed to clone 'vendor/grammars/typst-grammar' a second time, aborting
```

Looks like @michidk renamed the repo to just `typst`.

@michidk I see your repo is a fork of the upstream repo and is now trailing it. Should we switch to using the upstream grammar?

**Comment by michidk** [comment]
Hi @lildude so sorry about this. I deleted the repo since it was vastly out of date and people were complaining in the issues. I should have archived it instead.

Dont switch to `michidk/typst` this is the source code for the compiler and does not contain the grammar.

**Comment by lildude** [comment]
@michidk are you able to find another maintained grammar? If not the only option is to remove the current grammar which will upset a lot of Typst users, unless someone has a recent clone of your repo (I might, but there's no guarantee as I mostly use codespaces which are cleaned up regularly).

**Comment by michidk** [comment]
There are more up-to-date grammars, like https://github.com/Myriad-Dreamin/tinymist/tree/main/syntaxes/textmate but I dont think they are supported by linguist (at least I remember having a look at this and didnt get it to work, but maybe im wrong).
if you think it should work, I might have another look at it in future.

I have re-created the repository using information from other issues and PRs: https://github.com/michidk/typst-grammar/
For what its worth, I also added you as a maintainer.

I am not 100% sure its the latest version, so if you have a copy lying around feel free to post that here and I will have a look.

I am sorry for the inconvenience this caused.

Maybe a more future-proof version of this repository could host the grammars itself?

**Comment by lildude** [comment]
> I am not 100% sure its the latest version, so if you have a copy lying around feel free to post that here and I will have a look.

I do, and it's got the latest commit we're expecting to I'll force push my clone.

**Comment by lildude** [comment]
> There are more up-to-date grammars, like https://github.com/Myriad-Dreamin/tinymist/tree/main/syntaxes/textmate but I dont think they are supported by linguist (at least I remember having a look at this and didnt get it to work, but maybe im wrong).
> if you think it should work, I might have another look at it in future.

Nope. Looks like it needs some sort of preprocessing which we don't do.

> Maybe a more future-proof version of this repository could host the grammars itself?

We try not to host any grammars as there's an expectation that we'll maintain it which we won't 😁.

**Comment by michidk** [comment]
I think this can be closed then

**Comment by lildude** [comment]
> how often do you pull changes from [michidk/typst-grammar](https://github.com/michidk/typst-grammar/)? This would help us arrange tasks.

Whenever I make a new major or minor release, which happens approximately every three-four months as [detailed here](https://github.com/github-linguist/linguist/blob/main/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes).

> how could we test it in local (or continuously), so that we'll not break linguist on updating grammar?

We have a basic validator in the "[compiler](https://github.com/github-linguist/linguist/tree/main/tools/grammars)" which essential checks grammars are using valid PCRE regexps and then comers them all into JSON for the highlighting engine. This is run when you first [add a grammar](https://github.com/github-linguist/linguist/blob/5fad8d57605a914026a65b0e3ff6815d739944de/script/add-grammar#L132) to the repo and then I run it as part of the [release process](https://github.com/github-linguist/linguist/blob/main/docs/releasing.md) (pt 3.1 and 3.2) after updating the grammars.

You could probably script things up to do the same.

**Comment by michidk** [comment]
@Myriad-Dreamin I think a move of the repository will break this again. So best would be if typst-community were to fork my repo. But i totally agree that it would be the best move to have this under the hood of typst-community

**Comment by Myriad-Dreamin** [comment]
@lildude I have tested to ensure it to pass the checking of `grammar-compiler`. I also added a CI to ensure nothing will go bad. It should be great if you could give a look. I'm looking forward to linguist's next release.

**Comment by lildude** [comment]
> [@lildude](https://github.com/lildude) I have tested to ensure the new grammar to pass the checking of `grammar-compiler`. I also added a CI to ensure nothing will go bad. It should be great if you could give a look. I'm looking forward to linguist's next release.

@Myriad-Dreamin I'm not sure how you tested, but switching in your grammar doesn't work for me:

```console
➜ script/add-grammar https://github.com/Myriad-Dreamin/tinymist/ --replace vendor/grammars/typst-grammar/
Checking Docker is installed and running
Registering new submodule: https://github.com/Myriad-Dreamin/tinymist.git
Reactivating local git directory for submodule 'vendor/grammars/tinymist'
latest: Pulling from linguist/grammar-compiler
Digest: sha256:fcaf08a6e27d3d88212d9ca8aceee30d4089499a77bb05307871febd8073790f
Status: Image is up to date for linguist/grammar-compiler:latest
docker.io/linguist/grammar-compiler:latest
1 errors found in new grammar 'repository `vendor/grammars/tinymist` (from https://github.com/Myriad-Dreamin/tinymist.git)':
- Grammar conversion failed. File `editors/vscode/syntaxes/language-configuration.json` failed to parse: Undeclared scope in grammar: `editors/vscode/syntaxes/language-configuration.json` has no scope name

Compilation failed. Aborting

✘     
```

Note, this is finding the VSCode grammar (which is fine as it's a TextMate-compatible grammar), not the TextMate grammar.

All the grammars in your repo appear to require some sort of pre-processing. Linguist will not perform any pre-processing. It expects to find a fully "compiled" valid grammar in one of these locations, depending on the type of grammar:

https://github.com/github-linguist/linguist/blob/07486a12141a0803b511f9570e13ed5b45486e39/tools/grammars/compiler/loader.go#L119-L128

**Comment by lildude** [comment]
> [@lildude](https://github.com/lildude) The repository to use didn't switch. The built grammar is on the [michidk/typst-grammar](https://github.com/michidk/typst-grammar/)

Ah. That makes sense. Thanks for confirming. Those changes will def be pulled into the next release.
