### ISSUE TITLE
New language: Chaos

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#7152]
## Language name
Chaos

## URL of example repository
https://github.com/chaos-lang/chaos/tree/master/tests

## Most popular extensions

.kaos

**Comment by lildude** [comment]
This appears to be a hobby language with very few users on GitHub. Closing.

Ref: https://github.com/github-linguist/linguist/issues/6994#issuecomment-2287888666

As mentioned before, please refrain from opening issues like this.
